name: xiaojie-gui
version: '${version}'
main: io.github.heyhey123.xiaojiegui.XiaojieGUI
description: A Menu plugin for Skript, aimed at providing a user-friendly & high performance interface for Skript users to create and manage GUIs.
author: heyhey123
api-version: '${apiVersion}'
depend:
  - Skript
  - packetevents
softdepend:
  - SkBee
