name: Build

on:
  push:
    paths:
      - build.gradle.kts
      - src/**
      - .github/workflows/build.yml
  pull_request:
    paths:
      - build.gradle.kts
      - src/**
      - .github/workflows/build.yml

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
            # Cache Gradle dependencies and wrapper to speed up dependency resolution
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # keep key tied to relevant files so cache invalidates when build scripts or wrapper change
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts', '**/settings.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup java
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: build
        run: |
          ./gradlew clean build

      - uses: actions/upload-artifact@v4
        with:
          name: xiaojiegui-ubuntu-latest-${{ github.sha }}
          include-hidden-files: true
          path: |
           build/dist/
